### ISSUE TITLE
HttpError: Not Found

### ISSUE THREAD

**Issue by pradeepshekhawat29** [pauldraper/workflow-dispatch#2]
HttpError: Not Found
    at /home/runner/work/_actions/pauldraper/workflow-dispatch/v1.4/workflow-dispatch/dist/main.js:13876:27
    at processTicksAndRejections (node:internal/process/task_queues:96:[5]
    at async NextRunDispatcher.start (/home/runner/work/_actions/pauldraper/workflow-dispatch/v1.4/workflow-dispatch/dist/main.js:29798:2[6](

**Comment by bilaldjaghout** [comment]
I'm using v1.5 (tried v1.6) and I'm facing the same issue.
